osx_image: xcode7.3
language: objective-c

cache:
  - cocoapods
rvm:
  - 2.2.4

xcode_project: NSURL+QueryDictionary.xcodeproj
xcode_scheme: UnitTests

before_install: 
    - export LC_ALL="en_US.UTF-8"
    - gem install cocoapods

script: xcodebuild -project NSURL+QueryDictionary.xcodeproj -scheme UnitTests test
